---
title: "R Notebook"
output: html_notebook
---

### Set working directory:

```{r echo=TRUE}
setwd("~/fat/cancer_DNAm_distance/")
```

#### Load library:

```{r echo=TRUE}
library(ggplot2)
library(ggsci)
library(gridExtra)
library(foreach)
library(doParallel)
library(readr)
```

#### Adapter plot.

Read adapter content data.
```{r echo=TRUE}
dat <- read.csv("qc/adapter.tsv", header = F, sep = "\t", quote = "")
```

Draw plot.
```{r echo=TRUE}
ggplot(dat, aes(x = V2, y = V3)) +
  geom_line(aes(
    group = V1,
    color = V4,
    alpha = V5
  )) +
  guides(color = guide_legend(ncol = 1)) +
  xlab(label = "Position (bp)") +
  ylab(label = "% of sequences") +
  scale_x_continuous(
    breaks = seq(0, 150, 30),
    limits = c(0, 150),
    expand = c(0, 0)
  ) +
  scale_y_continuous(
    breaks = seq(0, 100, 10),
    limits = c(0, 100),
    expand = c(0, 0)
  ) +
  scale_alpha_continuous(
    breaks = seq(0.4, 1, 0.1),
    limits = c(0.4, 1),
    expand = c(0, 0),
    label = c("PN", "P20", "P15", "P10", "P5", "TE", "T")
  ) +
  theme(
    legend.background = element_blank(),
    legend.spacing = unit(0.1, units = "mm"),
    legend.key.size = unit(3.2, 0.2, units = "mm"),
    plot.title = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.background = element_blank(),
    panel.background = element_blank(),
    axis.line = element_line(colour = "#000000"),
    axis.ticks = element_line(colour = "#000000"),
    axis.ticks.length.y = unit(2, units = "mm"),
    axis.ticks.length.x = unit(1, units = "mm"),
    axis.title = element_text(
      colour = "#000000",
      face = "bold",
      size = 14
    ),
    axis.text = element_text(
      colour = "#000000",
      face = "bold",
      size = 12
    )
  )
```

#### Filter site plot.

Read site-filter data.
```{r}
dat <- read.csv("site_filter_input.tsv", header = F, sep = "\t", quote = "")
```

Draw plot.
```{r echo=TRUE}
dat$V1 <- as.factor(dat$V1)
ggplot(dat, aes(x = V3, y = (V4/V5*100))) +
  geom_line(aes(color = V1)) +
  xlab(label = "Coverage of each location") +
  ylab(label = "% of sites") +
  scale_x_continuous(
    breaks = c(5, 10, 15, 20, 30, 40, 50),
    limits = c(4, 51),
    expand = c(0, 0),
    labels = c("5X", "10X", "15X", "20X", "30X", "40X", "50X")
  ) +
  guides(color=guide_legend(title="Patient")) +
  scale_y_continuous(
    breaks = seq(0, 80, 10),
    limits = c(0, 80),
    expand = c(0, 0)
  ) +
  theme(
    legend.background = element_blank(),
    legend.spacing = unit(0.1, units = "mm"),
    legend.key.size = unit(3.2, 0.2, units = "mm"),
    plot.title = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.background = element_blank(),
    panel.background = element_blank(),
    axis.line = element_line(colour = "#000000"),
    axis.ticks = element_line(colour = "#000000"),
    axis.ticks.length.y = unit(2, units = "mm"),
    axis.ticks.length.x = unit(1, units = "mm"),
    axis.title = element_text(
      colour = "#000000",
      face = "bold",
      size = 14
    ),
    axis.text = element_text(
      colour = "#000000",
      face = "bold",
      size = 12
    )
  )
```

#### Spearman test.

Read site table of each sample and testing list.
```{r}
point_list <-
  read.csv(
    "site_venn.tsv",
    sep = "\t",
    header = F,
    row.names = 1
  )
colnames(point_list) <- (1:10)
point_list <- point_list[ order(as.numeric(row.names(point_list))), ]

P <- list()
for (i in (1:10)) {
  input_file <- paste("sitefilter15_P", sprintf("%02d", i), ".tsv", sep = "")
  dft <- read.csv(input_file,
                     sep = "\t",
                     header = F,
                     row.names = 1)
  colnames(dft) <- paste("P", (1:7), sep = "")
  P[[i]] <- data.frame(dft)
}
```

Spearman-rank test and plot drawing functions.
```{r}
do_spearman <- function(Site, Exp) {
  test_out <- cor.test(
    rep((1:7), sum(Exp)),
    do.call(c, lapply(as.numeric(colnames(Exp[, Exp == 1])), function(x)
      as.numeric(Site[[x]][rownames(Exp), ]))),
    conf.level = 0.95,
    method = "spearman",
    exact = FALSE
  )
  TP <- test_out$p.value
  SIG = 0
  if (!is.na(TP)) {
    if (TP < 0.05) {
      SIG = 1
    }
  }
  TR <- as.numeric(test_out$estimate)
  SP <- array(dim = 10)
  SR <- array(dim = 10)
  SSIG <- NULL
  SUM_SIG = 0
  for (i in as.numeric(colnames(Exp[, Exp == 1]))) {
    test_out <- cor.test(
      c(1:7),
      as.numeric(Site[[i]][rownames(Exp), ]),
      conf.level = 0.95,
      method = "spearman",
      exact = FALSE
    )
    SP[i] <- test_out$p.value
    SR[i] <- as.numeric(test_out$estimate)
    if (!is.na(test_out$p.value)) {
      if (test_out$p.value < 0.05) {
        SUM_SIG = SUM_SIG + 1
        SSIG <- c(SSIG, 0.88)
      } else{
        SSIG <- c(SSIG, 0.25)
      }
    } else {
      SSIG <- c(SSIG, 0.25)
    }
  }
  if (SUM_SIG > 0 | SIG > 0) {
    draw_plot(Site, Exp, SSIG, TP, TR)
    return(as.data.frame(cbind(
      rownames(Exp), sum(Exp), SUM_SIG, t(SP), t(SR), TP, TR
    )))
  }
}

draw_plot <- function(Site, Exp, Sig, TP, TR) {
  figfile <-
    paste("png/Site", rownames(Exp), ".png", sep = "")
  p <- ggplot() +
    geom_point(aes(x = rep((1:7), sum(Exp)),
                   y = do.call(
                     c, lapply(as.numeric(colnames(Exp[, Exp == 1])), function(x)
                       as.numeric(Site[[x]][rownames(Exp),]))
                   ))) +
    geom_line(aes(
      x = rep((1:7), sum(Exp)),
      y = do.call(c, lapply(as.numeric(colnames(Exp[, Exp == 1])), function(x)
        as.numeric(Site[[x]][rownames(Exp),]))),
      size = as.factor(rep(sprintf(
        "%02d", as.numeric(colnames(Exp[, Exp == 1]))
      ), each = 7)),
      color = as.factor(rep(sprintf(
        "%02d", as.numeric(colnames(Exp[, Exp == 1]))
      ), each = 7))
    )) +
    scale_color_jco(name = "Patient") +
    scale_x_continuous(
      breaks = c(1:7),
      limits = c(0.8, 7.2),
      expand = c(0, 0),
      labels = c("T", "TE", "P5", "P10", "P15", "P20", "PN")
    ) +
    scale_size_manual(values = Sig,
                      guide = 'none') +
    xlab(label = "Location") +
    ylab(label = "Beta value") +
    ggtitle(label = paste("P-value=", TP, "\nrho=", TR, sep = "")) +
    theme(
      legend.background = element_blank(),
      legend.spacing = unit(0.1, units = "mm"),
      legend.key.size = unit(3.2, 0.2, units = "mm"),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      plot.background = element_blank(),
      panel.background = element_blank(),
      axis.line = element_line(colour = "#000000"),
      axis.ticks = element_line(colour = "#000000"),
      axis.ticks.length.y = unit(2, units = "mm"),
      axis.ticks.length.x = unit(1, units = "mm"),
      axis.title = element_text(
        colour = "#000000",
        face = "bold",
        size = 14
      ),
      axis.text = element_text(
        colour = "#000000",
        face = "bold",
        size = 12
      )
    )
  png(figfile,
      type = "cairo",
      width = 1200,
      height = 800,
      res = 200)
  print(p)
  dev.off()
}
```

For-loop to calculate each site.
```{r}
output_path <- "Site.tsv"

write("==> Start parallel!", stderr())
for (ID in rownames(point_list)) {
  write(paste("==> Doing Site", ID, sep = ""), stderr())
  Site <- list()
  for (samp in 1:10) {
    Site[[samp]] <- round(P[[samp]][ID,], 0)
  }
  output <-
    do_spearman(Site, point_list[ID,])
  if (!is.null(output)) {
    write_delim(
      output,
      output_path,
      append = T,
      col_names = F,
      delim = "\t"
    )
  }
}
```

```{r}
chr.size = data.frame(
  chr1 = 0,
  chr2 = 249250621,
  chr3 = 492449994,
  chr4 = 690472424,
  chr5 = 881626700,
  chr6 = 1062541960,
  chr7 = 1233657027,
  chr8 = 1392795690,
  chr9 = 1539159712,
  chr10 = 1680373143,
  chr11 = 1815907890,
  chr12 = 1950914406,
  chr13 = 2084766301,
  chr14 = 2199936179,
  chr15 = 2307285719,
  chr16 = 2409817111,
  chr17 = 2500171864,
  chr18 = 2581367074,
  chr19 = 2659444322,
  chr20 = 2718573305,
  chr21 = 2781598825,
  chr22 = 2829728720,
  chr23 = 2881033286,
  stringsAsFactors = F
)

chr.size[2, ] <- c(paste0("chr", seq(1, 22, 1)), "end")
chr.size[1, ] <- as.numeric(chr.size[1, ])

chr.label <- data.frame()
for (i in seq(1, 22, 1)) {
  chr.label[1, paste0("chr", i)] <-
    (as.numeric(chr.size[1, paste0("chr", i)]) + as.numeric(chr.size[1, paste0("chr", i + 1)])) / 2
}
chr.label[2, ] <- paste0("chr", seq(1, 22, 1))

site_input <-
  read.csv(
    "site_venn_withinfo.tsv",
    header = F,
    row.names = 1,
    sep = "\t"
  )

dfraw <- site_input[, 1:2]
dfraw$X = NA
dfraw$Color = NA

for (i in paste0("chr", seq(1, 22, 1))) {
  dfraw[dfraw$V2 == i, ]$X = dfraw[dfraw$V2 == i, ]$V3 + as.numeric(chr.size[1, i])
  dfraw[dfraw$V2 == i, ]$Color = chr.size[2, i]
}
dfraw$Color <- as.factor(dfraw$Color)
dfraw <- na.omit(dfraw)

ggplot(dfraw) +
  geom_histogram(
    aes(x = X, fill = Color),
    show.legend = F,
    bins = 700,
    size = 0.5
  ) +
  scale_fill_manual(
    values = c(
      "#0073C2",
      "#EFC000",
      "#868686",
      "#CD534C",
      "#7AA6DC",
      "#003C67",
      "#8F7700",
      "#3B3B3B",
      "#A73030",
      "#4A6990",
      "#0073C2",
      "#EFC000",
      "#868686",
      "#CD534C",
      "#7AA6DC",
      "#003C67",
      "#8F7700",
      "#3B3B3B",
      "#A73030",
      "#4A6990",
      "#0073C2",
      "#EFC000"
    )
  ) +
  geom_vline(
    xintercept = as.numeric(chr.size[1,]),
    linetype = 1,
    alpha = 0.1
  ) +
  ylab(label = "Count") +
  xlab(label = "Chromosome") +
  scale_x_continuous(
    breaks = as.numeric(chr.label[1,]),
    label = chr.label[2,],
    expand = c(0.01, 0.01)
  ) +
  theme(
    plot.title = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    plot.background = element_blank(),
    panel.background = element_blank(),
    axis.line = element_line(colour = "#000000"),
    axis.ticks = element_line(colour = "#000000"),
    axis.ticks.length.y = unit(2, units = "mm"),
    axis.ticks.length.x = unit(1, units = "mm"),
    axis.title = element_text(colour = "#000000"),
    axis.text = element_text(colour = "#000000")
  )
```

```{r}
result <-
  read.csv(
    "result_spearman_filter00001.tsv",
    sep = "\t",
    header = F,
    row.names = 1
  )
dftt <-
  do.call(cbind, lapply(1:10, function(x)
    round(P[[x]][rownames(result),], 0)))
rownames(dftt) <- paste("S", rownames(result), sep = "")
colnames(dftt) <-
  paste("PA", rep(c(1:10), each = 7), "PO", rep(c(1:7), 10), sep = "")
filtered_dftt <-
  dftt[apply(
    dftt,
    MARGIN = 1,
    FUN = function(x)
      sd(x) != 0
  ), ]

dfttotal <-
  do.call(cbind, lapply(1:10, function(x)
    round(P[[x]][rownames(point_list),], 0)))

```


```{r}
anno <-
  data.frame(Patient = as.factor(rep(sprintf("%02d", c(
    1:10
  )), each = 7)),
  Position = as.factor(rep(
    c("T", "TE", "P5", "P10", "P15", "P20", "PN"), 10
  )))
rownames(anno) <-
  paste("PA", rep(c(1:10), each = 7), "PO", rep(c(1:7), 10), sep = "")

anno_col <- list(Patient = pal_jco()(10),
                 Position = c("#8c510a","#dfc27d","#c7eae5","#80cdc1","#35978f","#01665e","#003c30"))

names(anno_col$Patient) = as.factor(sprintf("%02d", c(1:10)))
names(anno_col$Position) = as.factor(c("T", "TE", "P5", "P10", "P15", "P20", "PN"))

pheatmap(
  dftt,
  scale = "row",
  na_col = "grey90",
  breaks = bk,
  color = c(colorRampPalette(colors = c(
    "#0000FF", "white", "#FF0000"
  ))(length(bk))),
  show_rownames = F,
  cutree_cols = 3,
  cutree_rows = 2,
  annotation_col = anno,
  annotation_colors = anno_col
)
```

